build:
    printf '%s\n%s\n%s\n\n' \
      '<!-- This file is generated from README.org, which is the' \
      '     authoritative source.  Do not edit this file directly.' \
      '     Run `just build` to regenerate it. -->' \
      > README.md
    pandoc --from org --to gfm README.org >> README.md
